[versions]
junit-jupiter = "5.12.1"


kotlin = "2.1.20"

paper = "2.0.0-beta.18"
paper-run = "2.3.1"

yml = "0.8.0"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter" }
junit-platform = { module = "org.junit.platform:junit-platform-launcher" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test-junit5" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

paper = { id = "io.papermc.paperweight.userdev", version.ref = "paper" }
paper-run = { id = "xyz.jpenilla.run-paper", version.ref = "paper-run" }

yml = { id = "de.eldoria.plugin-yml.bukkit", version.ref = "yml" }
