[versions]
junit-jupiter = "5.12.1"


kotlin = "2.1.20"

paper = "2.0.0-beta.18"
paper-convention = "1.3.0"
paper-run = "2.3.1"

shadow = "9.1.0"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter" }
junit-platform = { module = "org.junit.platform:junit-platform-launcher" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test-junit5" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

paper = { id = "io.papermc.paperweight.userdev", version.ref = "paper" }
paper-convention = { id = "xyz.jpenilla.resource-factory", version.ref = "paper-convention" }
paper-run = { id = "xyz.jpenilla.run-paper", version.ref = "paper-run" }

shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
